### ISSUE TITLE
we need a theme colour

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/ugwa2#6]
we don't need a secondary colour; just a primary

it should be red

**Comment by Velosify** [comment]
should it be slightly more saturated, bright, or have some other attributes

**Comment by SheepTester** [comment]
hmm

I would like saturated, but I'm usually the minority. Ask the Gamepwofive server

**Comment by SheepTester** [comment]
When you get a colour, use it on the [material UI demo](https://orbiit.github.io/ugwa2/demo/material-ui.html).

You'll have to use the developer tools to plug it in, but I helpfully made a JS thingy you can copypaste into the console to more easily test:
```js
((...rgb) => {
  rgb = rgb.join(', ');
  document.body.appendChild(createElement('style', {content: `
body {
  --primary: rgb(${rgb});
  --switch-on-track: rgba(${rgb}, 0.5);
}
.dark {
  --on-select-hover: rgba(${rgb}, 0.16);
  --on-select-focus: rgba(${rgb}, 0.24);
  --primary-ripple: rgba(${rgb}, 0.24);
}
.light {
  --on-select-hover: rgba(${rgb}, 0.08);
  --on-select-focus: rgba(${rgb}, 0.12);
  --primary-ripple: rgba(${rgb}, 0.12);
}
  `}));
})(244, 67, 54); // plug in the RGB values here
```

**Comment by Velosify** [comment]
I found `rgb(239, 43, 16)`
It looks okay

**Comment by SheepTester** [comment]
I swear I already responded? It had two images. Maybe I closed the tab before posting.

**Comment by SheepTester** [comment]
![screenshot 2018-06-27 at 12 14 50](https://user-images.githubusercontent.com/22133785/41975295-e75e2bb0-7a4c-11e8-8524-f20f068c0ec5.png)
![screenshot 2018-06-27 at 12 14 46](https://user-images.githubusercontent.com/22133785/41975296-e798a344-7a4c-11e8-9b2e-0fc6c4da9a9e.png)
*something alone the lines of poor contrast*

**Comment by Velosify** [comment]
oh so high contrast is requested

**Comment by Velosify** [comment]
which is not what I generally prefer

**Comment by SheepTester** [comment]
The red text doesn't look very good on the dark background. Red text on black generally is a bad idea. If you desaturate it, it'll make it like lighter and look better on dark.

Maybe you should make a light (and dark) version of the theme colour; the light version will be used on the input.

**Comment by SheepTester** [comment]
Also high contrast is always necessary. Why have text in the first place if people can't read it?

**Comment by Velosify** [comment]
I don't like too much contrast

**Comment by Velosify** [comment]
`rgb(247,8,8)`?

**Comment by SheepTester** [comment]
High contrast will be very helpful for people outside with a lot of glare.

> `rgb(250,8,8)`?
Still doesn't look very good on the input labels.

Maybe you could make a light version of the theme colour which'd be used for the inputs in dark theme.

**Comment by Velosify** [comment]
`rgb(234,76,76)` im still unaware how to check contrast so i will spam color values interminably (maybe)

**Comment by Velosify** [comment]
`rgb(255, 89, 89)` <- a likely brighter color

**Comment by SheepTester** [comment]
*(For reference, `#f44336` in RGB is `rgb(244, 67, 54)`)*

Using
```js
((...a)=>(
  document.body.style.setProperty('--primary', `rgb(${a})`),
  document.body.style.setProperty('--switch-on-track', `rgba(${a},.5)`)))
(234,76,76)
```
to test colours.

### Dark
![image](https://user-images.githubusercontent.com/22133785/45913746-e6178500-bded-11e8-99fc-2974606d3036.png)![image](https://user-images.githubusercontent.com/22133785/45913750-f62f6480-bded-11e8-998a-0c40c89d6879.png)![image](https://user-images.githubusercontent.com/22133785/45913754-0b0bf800-bdee-11e8-90ec-c464c60821ed.png)

### Light
![image](https://user-images.githubusercontent.com/22133785/45913756-1fe88b80-bdee-11e8-865c-81257b3733b0.png)![image](https://user-images.githubusercontent.com/22133785/45913762-31ca2e80-bdee-11e8-86dc-e8f0fa2b77b8.png)![image](https://user-images.githubusercontent.com/22133785/45913768-3ee71d80-bdee-11e8-9d0d-be25ee208328.png)

From left to right: current (material design), [the first one](https://github.com/Orbiit/ugwa2/issues/6#issuecomment-422689295), [the second one](https://github.com/Orbiit/ugwa2/issues/6#issuecomment-422689703)

**Comment by SheepTester** [comment]
The last one is rather pink; it makes it unique, and might distract from the fact that it's saturated. I was concerned that it wouldn't show up very well in light theme, but it actually shows up pretty well.

Thanks Steven!
